dt_save_to_disk: "3600secs"
rayleigh_sponge: true
initial_condition: "ScharProfile"
x_max: 120000.0
z_elem: 45
dt: "0.90secs"
t_end: "14400.0secs"
dz_top: 1000.0
x_elem: 100
dz_bottom: 50.0
use_reference_state: false
config: "plane"
kappa_4: 5.0e7
z_max: 25000.0
topography: "Schar"
job_id: "plane_schar_mountain_test_stretched"
toml: [toml/plane_schar_mountain_test_stretched.toml]
