dt_save_state_to_disk: "2days"
initial_condition: "DryBaroclinicWave"
dt: "400secs"
t_end: "1hours"
job_id: "sphere_baroclinic_wave_rhoe"
netcdf_output_at_levels: true
output_default_diagnostics: false
diagnostics:
  - short_name: [pfull]
    period: 1hours
