FLOAT_TYPE: "Float64"
h_elem: 30
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
dt: "100secs"
t_end: "120days"
initial_condition: "MoistBaroclinicWave"
moist: "equil"
precip_model: "0M"
dt_save_state_to_disk: "10days"
diagnostics:
  - short_name: [pfull, wa, va, rv, hus, ke]
    period: 1days
